// boss-data.js — challenge definitions for all module bosses
// Each challenge: { id, title, desc, starter, expectedOutput, hint }
// expectedOutput is trimmed and compared line-by-line against student output.

const BOSS_DATA = {
    0: {
        name: 'Den Tomme Skjermen',
        sprite: '👻',
        image: 'images/ghost.png',
        subtitle: 'Hjemsøker alle som ikke kan print()',
        bossHp: 400,
        attackTheme: { c1: '#e8f0ff', c2: '#7799cc', glow: '#aabbff' },
        attackMessages: [
            '👻 Spøkelset slukker skjermen din! −{n} HP',
            '👻 «Du glemte anførselstegnene!» −{n} HP',
            '👻 SyntaxError fra mørket! −{n} HP',
        ],
        timerMessages: [
            '👻 Spøkelset utnytter stillheten! −{n} HP',
            '👻 Den tomme skjermen angriper! −{n} HP',
        ],
        challenges: [
            {
                id: 'm0c1',
                title: 'Hei, verden!',
                desc: 'Det klassiske første programmet. Print: <em>Hei, verden!</em>',
                starter: '# Kode her',
                expectedOutput: 'Hei, verden!',
                hint: 'print("Hei, verden!")',
            },
            {
                id: 'm0c2',
                title: 'To linjer',
                desc: 'Print to linjer: først <em>Linje 1</em>, deretter <em>Linje 2</em>.',
                starter: '# To print()-kall',
                expectedOutput: 'Linje 1\nLinje 2',
                hint: 'To separate print()-kall, ett per linje',
            },
            {
                id: 'm0c3',
                title: 'Tom linje',
                desc: 'Print <em>Topp</em>, deretter en tom linje, deretter <em>Bunn</em>.',
                starter: '# print() tre ganger',
                expectedOutput: 'Topp\n\nBunn',
                hint: 'print("Topp"), print(""), print("Bunn")',
            },
            {
                id: 'm0c4',
                title: 'Navn og alder',
                desc: 'Print to linjer: <em>Navn: Python</em> og <em>Alder: 34</em>.',
                starter: '# To print()-kall',
                expectedOutput: 'Navn: Python\nAlder: 34',
                hint: 'print("Navn: Python") og print("Alder: 34")',
            },
            {
                id: 'm0c5',
                title: 'Tre stjerner',
                desc: 'Print tre linjer med stjerne-tegn: <em>*</em>, <em>**</em>, <em>***</em>.',
                starter: '# Tre print()-kall',
                expectedOutput: '*\n**\n***',
                hint: 'print("*"), print("**"), print("***")',
            },
        ],
    },

    1: {
        name: 'Variabel-Vampyren',
        sprite: '🧛',
        image: 'images/vampire.png',
        subtitle: 'Mester i variabler og datatyper',
        bossHp: 400,
        attackTheme: { c1: '#ff7777', c2: '#660000', glow: '#cc0000' },
        attackMessages: [
            '🧛 Vampyren suger energi fra variablene dine! −{n} HP',
            '🧛 «Variablene dine er mine!» roper Vampyren! −{n} HP',
            '🧛 Et angrep i mørket! −{n} HP',
        ],
        timerMessages: [
            '🧛 Vampyren utnytter nølinga di! −{n} HP',
            '🧛 Distrahert? Vampyren angriper! −{n} HP',
        ],
        challenges: [
            {
                id: 'v1',
                title: 'Stor by',
                desc: 'Variabelen <code>by = "oslo"</code> er gitt. Print den med store bokstaver.',
                starter: 'by = "oslo"\n# Kode her',
                expectedOutput: 'OSLO',
                hint: 'Strengmetoden .upper() gjør alle bokstavene store.',
            },
            {
                id: 'v2',
                title: 'Alder-printer',
                desc: 'Lag variablene <code>fornavn = "Ola"</code> og <code>alder = 16</code>. Print: <em>Ola er 16 år</em>',
                starter: '# Kode her',
                expectedOutput: 'Ola er 16 år',
                hint: 'print(fornavn, "er", alder, "år")',
            },
            {
                id: 'v3',
                title: 'Typejakt',
                desc: 'Print typen til verdien <code>3.14</code> (ikke til en variabel, direkte).',
                starter: '# Kode her',
                expectedOutput: "<class 'float'>",
                hint: 'print(type(3.14))',
            },
            {
                id: 'v4',
                title: 'Endringsmann',
                desc: 'Start med <code>poeng = 50</code>. Legg til 25. Trekk fra 10. Print <code>poeng</code>.',
                starter: 'poeng = 50\n# Gjør endringene og print',
                expectedOutput: '65',
                hint: 'poeng = poeng + 25, deretter poeng = poeng - 10',
            },
            {
                id: 'v5',
                title: 'Bool-bevis',
                desc: 'Lag variabelen <code>er_python_goy = True</code>. Print den.',
                starter: '# Kode her',
                expectedOutput: 'True',
                hint: 'Husk stor forbokstav på True!',
            },
        ],
    },

    2: {
        name: 'Løkke-Leviatan',
        sprite: '🐉',
        image: 'images/leviathan.png',
        subtitle: 'Herre over if-setninger og løkker',
        bossHp: 400,
        attackTheme: { c1: '#88ffff', c2: '#0033cc', glow: '#00aaff' },
        attackMessages: [
            '🐉 Leviatan sender en uendelig løkke! −{n} HP',
            '🐉 En falsk betingelse treffer deg! −{n} HP',
            '🐉 «Din kode looper for alltid!» −{n} HP',
        ],
        timerMessages: [
            '🐉 Leviatan utnytter pausen! −{n} HP',
            '🐉 While True! Leviatan angriper! −{n} HP',
        ],
        challenges: [
            {
                id: 'kf1',
                title: 'Positiv eller negativ',
                desc: '<code>tall = -7</code> er gitt. Print <em>positiv</em> om tall > 0, ellers <em>negativ</em>.',
                starter: 'tall = -7\n# if/else',
                expectedOutput: 'negativ',
                hint: 'if tall > 0: ... else: ...',
            },
            {
                id: 'kf2',
                title: 'Karaktersystem',
                desc: '<code>poeng = 75</code> er gitt. Print <em>A</em> om poeng ≥ 90, <em>B</em> om ≥ 70, ellers <em>C</em>.',
                starter: 'poeng = 75\n# if/elif/else',
                expectedOutput: 'B',
                hint: 'if poeng >= 90: ... elif poeng >= 70: ... else: ...',
            },
            {
                id: 'kf3',
                title: 'Opptelling',
                desc: 'Bruk en <code>while</code>-løkke til å printe tallene 1, 2, 3, 4, 5 (ett per linje).',
                starter: '# while-løkke\ni = 1',
                expectedOutput: '1\n2\n3\n4\n5',
                hint: 'while i <= 5: print(i), i += 1',
            },
            {
                id: 'kf4',
                title: 'Partallsjeger',
                desc: 'Print alle partall fra 0 til 10 inkludert (ett per linje). Bruk <code>for</code> og <code>range()</code>.',
                starter: '# for-løkke',
                expectedOutput: '0\n2\n4\n6\n8\n10',
                hint: 'range(0, 11, 2) gir partall 0–10',
            },
            {
                id: 'kf5',
                title: 'FizzBuzz-mini',
                desc: 'Print tallene 1–10. Om tallet er delelig med 3, print <em>Fizz</em> istedet.',
                starter: '# for i in range(1, 11):',
                expectedOutput: '1\n2\nFizz\n4\n5\nFizz\n7\n8\nFizz\n10',
                hint: 'if i % 3 == 0: print("Fizz") else: print(i)',
            },
        ],
    },

    3: {
        name: 'Funksjonenes Farao',
        sprite: '🏺',
        image: 'images/pharaoh.png',
        subtitle: 'Voktere av alle funksjoner',
        bossHp: 400,
        attackTheme: { c1: '#fff0a0', c2: '#aa7000', glow: '#ffcc00' },
        attackMessages: [
            '🏺 Farao kaller på feil funksjon! −{n} HP',
            '🏺 «Din funksjon returnerer None!» −{n} HP',
            '🏺 Udefinert funksjon-angrep! −{n} HP',
        ],
        timerMessages: [
            '🏺 Farao er utålmodig! −{n} HP',
            '🏺 Funksjonen din timed out! −{n} HP',
        ],
        challenges: [
            {
                id: 'fn1',
                title: 'Enkel funksjon',
                desc: 'Definer en funksjon <code>hils()</code> som printer <em>Hei, verden!</em>. Kall den deretter.',
                starter: '# def hils():',
                expectedOutput: 'Hei, verden!',
                hint: 'def hils(): \\n    print("Hei, verden!") \\nhils()',
            },
            {
                id: 'fn2',
                title: 'Dobler',
                desc: 'Definer funksjon <code>dobbel(x)</code> som printer <code>x * 2</code>. Kall <code>dobbel(7)</code>.',
                starter: '# def dobbel(x):',
                expectedOutput: '14',
                hint: 'def dobbel(x): \\n    print(x * 2)',
            },
            {
                id: 'fn3',
                title: 'Kvadrat',
                desc: 'Definer funksjon <code>kvadrat(n)</code> som <em>returnerer</em> n². Print <code>kvadrat(9)</code>.',
                starter: '# def kvadrat(n):',
                expectedOutput: '81',
                hint: 'def kvadrat(n): return n * n',
            },
            {
                id: 'fn4',
                title: 'Standard-hilsen',
                desc: 'Definer <code>hils(navn="Verden")</code> som printer <em>Hei, Verden!</em>. Kall uten argument.',
                starter: '# def hils(navn="Verden"):',
                expectedOutput: 'Hei, Verden!',
                hint: 'def hils(navn="Verden"): print(f"Hei, {navn}!")',
            },
            {
                id: 'fn5',
                title: 'Innebygd magi',
                desc: '<code>tall = [3, 1, 4, 1, 5, 9, 2, 6]</code> er gitt. Print summen av alle tallene.',
                starter: 'tall = [3, 1, 4, 1, 5, 9, 2, 6]\n# En linje',
                expectedOutput: '31',
                hint: 'print(sum(tall))',
            },
        ],
    },

    4: {
        name: 'Datastruktur-Dragen',
        sprite: '🐙',
        image: 'images/dragon.png',
        subtitle: 'Arkivaren av lister og ordbøker',
        bossHp: 400,
        attackTheme: { c1: '#ee88ff', c2: '#550088', glow: '#aa00cc' },
        attackMessages: [
            '🐙 Dragen blander alle listene dine! −{n} HP',
            '🐙 IndexError! −{n} HP',
            '🐙 KeyError treffer deg! −{n} HP',
        ],
        timerMessages: [
            '🐙 Dragen spiser datastrukturen din! −{n} HP',
            '🐙 Listene kollapser! −{n} HP',
        ],
        challenges: [
            {
                id: 'ds1',
                title: 'Liste-indeks',
                desc: '<code>frukter = ["eple", "banan", "appelsin", "mango"]</code>. Print den tredje frukten (indeks 2).',
                starter: 'frukter = ["eple", "banan", "appelsin", "mango"]\n# Kode her',
                expectedOutput: 'appelsin',
                hint: 'frukter[2]',
            },
            {
                id: 'ds2',
                title: 'Liste-manipulasjon',
                desc: '<code>tall = [1, 2, 3]</code>. Legg til 4 med append. Fjern 2 med remove. Print listen.',
                starter: 'tall = [1, 2, 3]\n# append og remove',
                expectedOutput: '[1, 3, 4]',
                hint: 'tall.append(4) så tall.remove(2)',
            },
            {
                id: 'ds3',
                title: 'Ordbok-oppslag',
                desc: '<code>person = {"navn": "Ola", "alder": 17, "by": "Oslo"}</code>. Print personens by.',
                starter: 'person = {"navn": "Ola", "alder": 17, "by": "Oslo"}\n# Kode her',
                expectedOutput: 'Oslo',
                hint: 'print(person["by"])',
            },
            {
                id: 'ds4',
                title: 'Liste-løkke',
                desc: '<code>dyr = ["katt", "hund", "fugl"]</code>. Print hvert dyr med STORE bokstaver, ett per linje.',
                starter: 'dyr = ["katt", "hund", "fugl"]\n# for-løkke',
                expectedOutput: 'KATT\nHUND\nFUGL',
                hint: 'for d in dyr: print(d.upper())',
            },
            {
                id: 'ds5',
                title: 'Ordbokkeys',
                desc: '<code>karakterer = {"Matte": 5, "Norsk": 4, "Gym": 6}</code>. Print alle fagnavn (kun nøklene), ett per linje.',
                starter: 'karakterer = {"Matte": 5, "Norsk": 4, "Gym": 6}\n# for k in ...',
                expectedOutput: 'Matte\nNorsk\nGym',
                hint: 'for fag in karakterer: print(fag)',
            },
        ],
    },

    5: {
        name: 'Feil-Føniks',
        sprite: '🔥',
        image: 'images/phoenix.png',
        subtitle: 'Mesteren av unntak og moduler',
        bossHp: 400,
        attackTheme: { c1: '#ffee44', c2: '#cc2200', glow: '#ff6600' },
        attackMessages: [
            '🔥 Føniks kaster en ukjent exception! −{n} HP',
            '🔥 ModuleNotFoundError treffer! −{n} HP',
            '🔥 «Koden din krasjer!» ler Føniks! −{n} HP',
        ],
        timerMessages: [
            '🔥 Føniks brenner koden din! −{n} HP',
            '🔥 TimeoutError fra Føniks! −{n} HP',
        ],
        challenges: [
            {
                id: 'fm1',
                title: 'Sikker divisjon',
                desc: '<code>tall = 10; divisor = 0</code>. Bruk try/except for å printe <em>Kan ikke dele på null!</em> ved ZeroDivisionError.',
                starter: 'tall = 10\ndivisor = 0\n# try/except',
                expectedOutput: 'Kan ikke dele på null!',
                hint: 'try: print(tall / divisor) except ZeroDivisionError: ...',
            },
            {
                id: 'fm2',
                title: 'Type-konvertering',
                desc: '<code>tekst = "abc"</code>. Prøv int(tekst) med try/except. Skriv ut <em>Ugyldig tall</em> ved ValueError.',
                starter: 'tekst = "abc"\n# try/except ValueError',
                expectedOutput: 'Ugyldig tall',
                hint: 'try: print(int(tekst)) except ValueError: print("Ugyldig tall")',
            },
            {
                id: 'fm3',
                title: 'Mattemodul',
                desc: 'Importer <code>math</code>. Print <code>math.floor(math.pi)</code>.',
                starter: 'import math\n# math.floor(math.pi)',
                expectedOutput: '3',
                hint: 'print(math.floor(math.pi))',
            },
            {
                id: 'fm4',
                title: 'Kvadratrot',
                desc: 'Importer <code>math</code>. Print kvadratroten av 144.',
                starter: 'import math\n# math.sqrt()',
                expectedOutput: '12.0',
                hint: 'print(math.sqrt(144))',
            },
            {
                id: 'fm5',
                title: 'Finally-blokk',
                desc: 'Prøv å dele 100 på 0. Print <em>Feil: deling med null</em> ved unntak. Bruk finally til å printe <em>Ferdig.</em>',
                starter: '# try / except / finally',
                expectedOutput: 'Feil: deling med null\nFerdig.',
                hint: 'try: ... except: print("Feil: deling med null") finally: print("Ferdig.")',
            },
        ],
    },
};
